#! /bin/sh
PIDFILE='/usr/local/var/run/noip.pid'


start() {
      echo "Starting noip2\n"
        /usr/local/bin/noip2
    timeout=30
    while ps aux | grep 'noip2' | grep -e 'local'; do
      echo -n '>'
        for i in `sudo noip2 -S 2>&1 | grep Process | awk '{print $2}' | tr -d ','`
        do
          echo $i > $PIDFILE 
        done
	timeout=$((timeout-1))
      if [ $timeout -lt '1' ]; then return; fi
      sleep 1
    done;
}

stop() {
        echo -n "Shutting down noip2\n"
        if [ -f $PIDFILE  ]; then
          echo "[pidfile exist]"
	else
          echo "[pidfile does not exist]"
          killproc -TERM /usr/local/bin/noip2
        fi
        for i in `sudo noip2 -S 2>&1 | grep Process | awk '{print $2}' | tr -d ','`
        do
          noip2 -K $i
	  if [ -f $PIDFILE ]; then
            rm $PIDFILE
	  fi
        done
}

restart() {
	stop
    timeout=30
    while ps aux | grep 'noip2' | grep -e 'local'; do
      echo -n '.'
        stop
	timeout=$((timeout-1))
      if [ $timeout -lt '1' ]; then return; fi
      sleep 1
    done;
	start
}

case "$1" in
    start)
	start
    ;;
    stop)
	stop
    ;;
    restart)
	restart
    ;;
    status)
        if [ -f $PIDFILE  ]; then
          echo "[noip2 is running]"
        else
          echo "[noip2 is not running]"
        fi
    ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
esac
exit 0
